### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by a-sche** [cran/rWCVP#1]
When trying to install the package I receive an error that hints to one of your functions: 
----
_Error in parse(outFile) : 
     C:/.../rWCVP/R/wcvp_checklist.R:143:36: unexpected '>'
   142:   endemics <- distribution %>%
   143:     group_by(.data$plant_name_id) |>
                                           ^
   ERROR: unable to collate and parse R files for package 'rWCVP'
-  removing 'C:/.../RtmpG0bZ1T/Rinst75d416874a9a/rWCVP'_
----
In wcvp_checklist Line 143 should this be %>% instead? 

Thank you!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by a-sche** [comment]
okay thank you!
